spring:
  application:
    name: rollenspiel-cons
    description: Rollenspiel PhysicalEvent Management
    version: 999.999-SNAPSHOT
  main:
    banner-mode: log
  config:
    import: classpath:local.properties
    
ingress:
  host: localhost:8080